WIKI-1248 :HOW-TO Guide template and Three-Column Layout template doe…
exoplatform/wiki pull request #188
Opened 2016-08-30 12:35 UTC by azaoui

WIKI-1248 :HOW-TO Guide template and Three-Column Layout template isn't work

2016-08-31 11:02 UTC, boubaker commented on wiki-webui/src/main/java/org/exoplatform/wiki/commons/Utils.java
> -    xhtmlContent = StringCommonUtils.encodeScriptMarkup(xhtmlContent);
Don't delete the sanitizer, but improve it to fix the problem and the original XSS issue.

2016-08-31 11:27 UTC, azaoui commented on wiki-webui/src/main/java/org/exoplatform/wiki/commons/Utils.java
> -    xhtmlContent = StringCommonUtils.encodeScriptMarkup(xhtmlContent);
Ok will try other approach, but please note that reasons for reverting are listed in the jira issue and the fix was made to fix the maintenance branch 4.3.x as a deeply fix will be made for 4.4 and can't be backported for the moment as new  
sanitizer lib will be used.

2017-01-12 08:49 UTC, boubaker requested changes

2017-01-12 08:49 UTC, boubaker commented on wiki-webui/src/main/java/org/exoplatform/wiki/commons/Utils.java
> -    xhtmlContent = StringCommonUtils.encodeScriptMarkup(xhtmlContent);
Please refresh the PR with new Wiki Sanitization API introduced in Wiki.

2020-10-02 11:05 UTC, closed without merging